#!/usr/bin/with-contenv sh

# Installation UUID must be informed
if [ -z "$DASPANEL_SYS_UUID" ]; then
    echo "***"
    echo "ERROR: You must set the env variable DASPANEL_SYS_UUID to a valid UUID"
    echo "***"
    exit 1
fi

exec su-exec daspanel:daspanel /usr/sbin/minio --config-dir=/etc/minio server "/opt/daspanel/data"

