
# Minio Fileserver

Docker image that provides volumes to be shared with other containers of Daspanel system. It also provides an S3 compatible server using Minio.

* Free software: MIT license
* Documentation: https://github.com/daspanel/minio-fileserver

## Environment variables
| Variable | Optional      | Example Value | Purpose
|----------|---------------|---------------|---------------|
| DASPANEL_GUUID | yes | ksdf09832klsdfkjsdlk | UUID used in Daspanel system to identify a unique instance of data. If you don't provide one Daspanel generate it using [Getuuid API](https://9jzojg54n7.execute-api.us-east-1.amazonaws.com/v1/uuid)|
| DASPANEL_MASTER_PASSWORD | yes | SomeGood#%@Passwd123 | Password to be used in the various Daspanel services. Automatically generated if you do not provide one.
| DASPANEL_MASTER_EMAIL | no | your@email.com | Email of the owner of Daspanel instance. It can be used for receiving notifications from the system. The Docker container will not run if it is not informed.

You can find the value of variables automatically generated by examining the 
container log after it starts. Or looking at the output of the console where 
you run your docker.

## How to use
Get
```shell
docker pull daspanel/minio-fileserver:latest
```

Run
```shell
docker run -e DASPANEL_MASTER_EMAIL=my@email.com daspanel/minio-fileserver:latest
```

## Features

* Alpine Linux with S6 overlay

!!! warning "WIP"
    Wordk in progress.

## Credits

* This project was auto created with <https://github.com/daspanel/cookiecutter-docker>
* [Mkdocs](http://www.mkdocs.org/)
* [CHANGELOG.md Generator](https://github.com/mh-cbon/changelog)
* <https://github.com/deweysasser/docker-project-template>
* <https://github.com/zixia/docker-simple-mail-forwarder>
* <https://github.com/mvanholsteijn/docker-makefile>
* <https://github.com/sstephenson/bats>
* <https://github.com/webhippie/templater>
* <https://stedolan.github.io/jq/>

